[workspace]
members = [
    "definition",
    "database",
    "api",
    "services",
]

[package]
name = "mcep"
version = "0.1.0"
edition = "2021"
target = "src/main.rs"

[dependencies]
api = { path = "api"}

tokio = { version = "1", features = ["macros", "rt-multi-thread"] }