[workspace]
members = [
    "definition",
    "database",
    "api",
    "services",
]

[package]
name = "mcep"
version = "0.1.0"
edition = "2021"


[dependencies]
api = { path = "api"}
database = { path = "database" }

tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }