version: '3.8'
services:
  psql:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=mcep
      - POSTGRES_PASSWORD=mcep
    ports:
      - '5432:5432'
  zookeeper:
    container_name: zookeeper
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=input:1:1,output:1:1
    depends_on:
      - zookeeper