include:
  - docker-compose.yaml
services:
  mcep:
    - image: docker.io/mcep
      build:
        context: ../
      ports:
        - 8080:8080
      environment:
        - DATABASE_URL=postgres://mcep:mcep@localhost:5432/mcep
        - DEBUG_ENABLED=true