debug=false
[database]
host="localhost"
port=5432
user="mcep"
password="mcep"
name="mcep"

[kafka]
hosts=["localhost:9092"]
topics.input="input"
topics.output="output"
client_id="mcep"

[logging]
debug=false